services:
  app:
    container_name: youtube_bot
    image: ilmuflone/telegram-youtube-bot:0.1.1
    restart: unless-stopped
    networks:
      - default
    env_file:
      - ./app.env
    volumes:
      - "./data:/app/data:ro"

networks:
  default:
    name: youtube_bot
    driver: bridge
    enable_ipv6: false

